### ISSUE TITLE
能够提供一个入口便于对窗口进行美化?

### ISSUE THREAD

**Issue by fang2hou** [tg123/myslot#11]
我是 [ElvUI_WindTools](https://github.com/fang2hou/ElvUI_WindTools) 的作者.
插件内部包含了一些常用插件的皮肤以达到整体 UI 风格的统一.

最近想为 MySlot 制作一个 ElvUI 阴影风的皮肤, 但是貌似 MySlot 没有注册全局变量, 请问能否在后续更新之中释放 GUI 窗口到全局变量中呢? (比如: `MySlotGUI = f`)

**Comment by tg123** [comment]
我可以在Addon上加一个

**Comment by fang2hou** [comment]
感谢~
顺便提醒一下版本号现在已经来到 9.0.2 了, 需要稍微更新一下 toc

**Comment by tg123** [comment]
`LibStub('Myslot-5.0').MainFrame`
