### ISSUE TITLE
Ignore Macros unexpected behavior

### ISSUE THREAD

**Issue by trying-to-function** [tg123/myslot#17]
I want to ignore the import/export of macros, but I also want the action bar import/export to include macros.

Please advise

**Comment by tg123** [comment]
this is not doable
macroid in wow is random, importing marcoid could be different from what you export.

**Comment by chrisblossom** [comment]
As long as you do not have duplicate macro names it should not be an issue

**Comment by trying-to-function** [comment]
As long as you do not have duplicate macro names it should not be an issue.

**Comment by tg123** [comment]
myslot is designed to `copy and paste exactly` what was exported.
no plan to support `named macro matching` at the moment.

fork and build your own is welcomed
