### ISSUE TITLE
Enhancement: Export/Import Talents

### ISSUE THREAD

**Issue by hewozuoai** [tg123/myslot#18]
Would be nice to be able to export/import talents (assuming in a rested area)

**Comment by tg123** [comment]
i believe there are so many talent exporters addoons right?

**Comment by hewozuoai** [comment]
I use MySlot with SpecSpecificKeybinds addon so for example as a druid i can have multiple bar/macro setups for balance (pvp necro, pvp nf, pve nf, pve venth etc) and when you load a config with MySlot it sorts that stuff out perfectly. The only other changes that i forget to make are the main talents.

Here is the code i tested yesterday, i will test adding it to MySlot later to see if it works.

```
--exporting talents
local s = GetActiveSpecGroup()
for t =1, MAX_TALENT_TIERS do
    for c = 1, NUM_TALENT_COLUMNS do
        id, _, _, on,_,_,_,_,_,_,_=GetTalentInfo(t,c,s)
        if on then
            -- save to msg.talents ?
            print(id)
        end
    end
end
```

```
--importing talents
local ts = {22385,18571,22157,18576,21702,22389,21193} -- get from msg.talents ?
if IsResting() then
    for _,t in ipairs(ts) do
        s = LearnTalent(t)
    end
end
```

**Comment by tg123** [comment]
in old days when i was playing wow, you have to pay for reset talent, is it true today?
if it is free, importing talent together is acceptable.
