### ISSUE TITLE
Is there a version that supports Lightshope?

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [tg123/myslot#2]
Thanks ^_^

**Comment by tg123** [comment]
https://www.wowace.com/projects/myslot/files

classic?

**Comment by LakeishaKowalczyk** [comment]
a fans server, unofficial server
https://lightshope.org/

**Comment by tg123** [comment]
classic version supports 1.13.x, not sure if compatible with lightshope

**Comment by LakeishaKowalczyk** [comment]
![image](https://user-images.githubusercontent.com/14090545/63016331-f7fe8c80-bec5-11e9-8eda-5999098874c9.png)

Thanks, Looks like incompatible
