### ISSUE TITLE
Make addon importable in WoWup

### ISSUE THREAD

**Issue by Faycop** [tg123/myslot#24]
Hi, thanks again for the support in #23 . I'm writing you this time to ask if you could make an adjustment to your repo to make it  importable in [WoWup](https://wowup.io/).

A guide that shows how to set up the repo is available in [WoWup's documentation](https://wowup.io/guide/get-addons/overview).

Other addons repos like [SavedInstances](https://github.com/SavedInstances/SavedInstances) and [Leatrix Plus](https://github.com/leatrix/leatrix-plus) can be easily added.

Thank you for the good work!

**Comment by tg123** [comment]
THsi is weird, I have https://www.curseforge.com/wow/addons/myslot
but seems not recognized by wowup

**Comment by Faycop** [comment]
WoWup supports GitHub urls, but as you can see in the screenshot for this repo gives me an undefined error
![Screenshot (73)](https://user-images.githubusercontent.com/1913375/198511435-92944f35-270c-4257-ad17-05b1347402fe.png)

**Comment by tg123** [comment]
https://www.wowhead.com/news/wowup-launches-new-addon-manager-supporting-curseforge-downloads-329736

**Comment by tg123** [comment]
Curse now supported
![image](https://user-images.githubusercontent.com/170430/200146502-11074053-abc3-40b6-b330-bb721824d899.png)
