### ISSUE TITLE
Ignore Rank of spells

### ISSUE THREAD

**Issue by michael-lucas-net** [tg123/myslot#28]
Is it possible to ignore the rank of a spell (in wotlk classic)?

e.g. I have a 80 warlock and want to myslot my 61 warlock.

When i myslot them, it will show lvl 80 ranks of spells (that i dont have on my 61 warlock - e.g. "Unstable Affliction" Rank3 , but i only have learned rank2)

**Comment by tg123** [comment]
I am thinking add a smart match if spell is not learned
same issue as #27
