### ISSUE TITLE
WoWUp compatability

### ISSUE THREAD

**Issue by Yitaarli** [tg123/myslot#30]
Hello,

First of all, thank you for your work on this addon. 

I appreciate that you addressed the wowup compatability issue in a previous issue, however, although they have now released a curseforge compatible version of wowup, this program still requires the installation of a propriatory version of electron that Overwolf themselves have written.  They have not, as far as I know, disclosed to WoWUp developers or users what exactly is contained in their version of electron and given their dubious history, a significant number of users (including myself) have decided not to install it and stick with the wago version. 

Therefore, would you still consider putting this addon on a WoWUp compatible website (e.g. Wago, wowinterface, github). If you want to discuss this or need instructions on how to do this you can find them on the WoWup discord server: https://discord.gg/vGsW24qx (link expires in 7 days)

Thank you for your consideration.

**Comment by tg123** [comment]
Thanks
the addon build highly depends on curseforge localization system
I do not think it is an easy move
