### ISSUE TITLE
LUA Error

### ISSUE THREAD

**Issue by westlakem** [tg123/myslot#31]
Was trying to copy settings to PTR.  I am able to click export and have it generate the text, however when I click on the test to copy it I get this error.

![image](https://user-images.githubusercontent.com/4505074/236706516-23e93c4f-ee43-4f96-990e-4e2ab779662b.png)

**Comment by tg123** [comment]
click `text` to copy it right?

let me check on ptr, 10.0+ right?

**Comment by tg123** [comment]
fixed in https://www.curseforge.com/wow/addons/myslot/files/4633268
