### ISSUE TITLE
limit of 50?

### ISSUE THREAD

**Issue by AbooseYou** [tg123/myslot#33]
Hi
limit on only making 50 saved layouts once i hit 50 it starts removing old ones to make new ones is this a bug?

**Comment by tg123** [comment]
hmmm, what is the best option for you?

**Comment by tg123** [comment]
what about pop an err to ask for clean up if 50 reached

**Comment by tg123** [comment]
profile is not class specific from day 1 of myslot
it also encourages to import setting from different class

i will make the max profile count adjustable via settings

**Comment by tg123** [comment]
set to 100 and will not trim any more #67
