### ISSUE TITLE
WoW Classic Era Update [Version 1.14.4]

### ISSUE THREAD

**Issue by maximus210793** [tg123/myslot#35]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game Version of 1.14.4?
Would be awesome, thanks a lot in advance!

**Comment by tg123** [comment]
let me check, anything not working when using load out date addon?

**Comment by maximus210793** [comment]
Just a update for version 1.14.4 would be great :)

**Comment by tg123** [comment]
https://www.wowace.com/projects/myslot/files/4821202
