### ISSUE TITLE
can not found in curse

### ISSUE THREAD

**Issue by zhb005** [tg123/myslot#36]
can not search in curse，and After installation, execute prompt belongs to 'another game flavor‘
<img width="929" alt="1698652916045" src="https://github.com/tg123/myslot/assets/70770482/5a867c11-3555-45d3-ad33-bc482616486b">
<img width="773" alt="1698653011604" src="https://github.com/tg123/myslot/assets/70770482/8efac5ec-c493-45c9-b9e1-c06d5f899a97">

**Comment by tg123** [comment]
could you please try again

**Comment by zhb005** [comment]
Now it's okay, thanks!
