### ISSUE TITLE
doesn't put macros on action bars

### ISSUE THREAD

**Issue by Asilartus** [tg123/myslot#37]
when I import macros are copied but not into action bars, I have to manually find each and put into position. It used to do that, any ideas where cd be a problem?

**Comment by Asilartus** [comment]
so far what I tested:
new problem [Swipe] and [Thrash] are saved as passives: [Mastery: Nature's Guardian] and [Ursine Adept]
some (2/3) macros are loaded into action bars, 1/3 never and from those 2/3 that are loaded I have no idea why but sometimes even they are not in action bars
reinstalling with "delete all settings" didn't help
disabling all other addons also didn't help
;(

**Comment by tg123** [comment]
could you please paste 
wow ver
myslot ver

and your export text for me to verify

**Comment by Asilartus** [comment]
wow 10.2
myslot one from 10/28/2023 I use curse
sent export text to ur @
<3

**Comment by tg123** [comment]
help needed

1 make sure first slot of actionbar 1 has the macro that did not show after import
![image](https://github.com/tg123/myslot/assets/170430/a9bab392-88bc-4c2d-b1f9-a7bc6f5c7bef)
2 run `/dump GetActionInfo(1)` and copy result to me
![image](https://github.com/tg123/myslot/assets/170430/31a5130d-1292-4797-8d1f-e20a7fccd52f)
![image](https://github.com/tg123/myslot/assets/170430/7ef63ee9-7d37-41f7-b2db-c29f7cc76ac5)

**Comment by Asilartus** [comment]
![image](https://github.com/tg123/myslot/assets/119135426/b938cc1b-8e08-4601-b2e2-c0906feb5f08)

**Comment by tg123** [comment]
please test https://www.curseforge.com/wow/addons/myslot/files/4861148

however, old corrupted exported cannot be imported anymore, sorry about it

**Comment by Asilartus** [comment]
everything works for me, thanks love u <3

**Comment by tg123** [comment]
@Asilartus your input is very helpful
