### ISSUE TITLE
Classic Era Update 1.15.0 (Season of Discovery)

### ISSUE THREAD

**Issue by maximus210793** [tg123/myslot#39]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.0 (Season of Discovery)?
Would be awesome, thanks a lot in advance!

**Comment by tg123** [comment]
not fully tested as i do not have 25 account, any issue with current version?

**Comment by maximus210793** [comment]
The Version V1.15 is not supported and therefore showing error, could you update the version therefore?

**Comment by tg123** [comment]
could you please paste me error you saw?

**Comment by maximus210793** [comment]
Can you update the Version to 1.15.0 ?
For me it is still saying 1.14.4.
Thanks in advance!

**Comment by tg123** [comment]
[done](https://www.wowace.com/projects/myslot/files/5000443)
