### ISSUE TITLE
UnifyCRLF 有问题

### ISSUE THREAD

**Issue by leifan8440** [tg123/myslot#4]
local name, _, body = GetMacroInfo(i)
        body = UnifyCRLF(body)

GetMacroInfo(i) nil的时候会报错
应该body = UnifyCRLF(body)移到
if name then 下面去

**Comment by tg123** [comment]
足下所言甚是
何不发个PR

**Comment by leifan8440** [comment]
我...不会用git啊，不是程序员，只是简单能看懂代码

**Comment by tg123** [comment]
fixed 4d4b0e0
