### ISSUE TITLE
deleted all my settings

### ISSUE THREAD

**Issue by Goten87** [tg123/myslot#40]
i know there is a warning in the Settings but i clicked the delete or clean action bars button
to clean my action bars and well it deleted all settings compleetly

so now i lost my macros and keybindings i think there is a bug

**Comment by tg123** [comment]
you have to check clean macro and clean keybinding, i believe you selected all three

what is the expected behavior?

**Comment by Goten87** [comment]
i selected none i did it from the settings windows

**Comment by Goten87** [comment]
![image](https://github.com/tg123/myslot/assets/1938598/8dfa81be-367d-4933-9540-c5357b8eca32)
i only clicked the Remove Evrything in actionbar but it deleted as well my global macros and keybindings
is the actionbar not only for the icons in there

**Comment by tg123** [comment]
oh really, let me double check
it should not remove macro nor bindings

**Comment by Goten87** [comment]
huh now it works oke O.o wierd

**Comment by tg123** [comment]
tested and revisited the code
the `clean` will clean one type at a time only

**Comment by Goten87** [comment]
also maby put some text on top of the check boxes what they are for (all the ignore are for export i think and all the clear is import settings maby put it above it as text)

**Comment by Goten87** [comment]
but its working for me now as well oke just tested it like 3 times or so

**Comment by tg123** [comment]
thanks for confirming
