### ISSUE TITLE
duplicate macros after import

### ISSUE THREAD

**Issue by axbcn** [tg123/myslot#51]
Clear all settings and import with duplicate macros
![1111](https://github.com/tg123/myslot/assets/174179953/c5421cd4-7a74-454c-9d2d-b1d8255ff52a)

**Comment by tg123** [comment]
You can first use ·/myslot clear· to delete it so it won’t cause duplicate issues. I am investigating the reason

**Comment by tg123** [comment]
fixed in https://www.curseforge.com/wow/addons/myslot/files/5485299
