### ISSUE TITLE
Lua error 5.17.0

### ISSUE THREAD

**Issue by zeenk** [tg123/myslot#53]
1x Myslot/gui.lua:307: attempt to concatenate global 'ACTIONBAR_LABEL' (a nil value)
[string "@Myslot/gui.lua"]:307: in function `CreateSettingMenu'
[string "@Myslot/gui.lua"]:379: in main chunk

Locals:
opt = <table> {
 ignorePetActionBar = false
 ignoreActionBars = <table> {
 }
 ignoreBinding = false
 ignoreMacros = <table> {
 }
}
tableref = <function> defined @Myslot/gui.lua:69
childchecked = <function> defined @Myslot/gui.lua:83
childclicked = <function> defined @Myslot/gui.lua:87
parentchecked = <function> defined @Myslot/gui.lua:93
parentclicked = <function> defined @Myslot/gui.lua:104
actionbarlist = <table> {
 1 = <table> {
 }
 2 = <table> {
 }
 3 = <table> {
 }
 4 = <table> {
 }
 5 = <table> {
 }
 6 = <table> {
 }
 7 = <table> {
 }
 8 = <table> {
 }
 9 = <table> {
 }
 10 = <table> {
 }
 11 = <table> {
 }
 12 = <table> {
 }
 13 = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = <table> {
 hasArrow = true
 checked = <function> defined @Myslot/gui.lua:93
 notCheckable = false
 isNotRadio = true
 func = <function> defined @Myslot/gui.lua:104
 arg1 = "action"
 keepShownOnClick = true
 menuList = <table> {
 }
}
(*temporary) = <table> {
 checked = <function> defined @Myslot/gui.lua:272
 keepShownOnClick = true
 notCheckable = false
 text = "Key Binding"
 func = <function> defined @Myslot/gui.lua:269
 isNotRadio = true
}
(*temporary) = <table> {
 hasArrow = true
 checked = <function> defined @Myslot/gui.lua:93
 notCheckable = false
 text = "Macro"
 func = <function> defined @Myslot/gui.lua:104
 arg1 = "macro"
 keepShownOnClick = true
 menuList = <table> {
 }
 isNotRadio = true
}
(*temporary) = <table> {
}
(*temporary) = "Pet"
(*temporary) = " "
(*temporary) = nil
(*temporary) = "%s Specific Macros"
(*temporary) = ""
(*temporary) = "attempt to concatenate global 'ACTIONBAR_LABEL' (a nil value)"
menuFrame = Frame {
 0 = <userdata>
 Text = UIParentText {
 }
 Icon = UIParentIcon {
 }
 Button = UIParentButton {
 }
 Right = UIParentRight {
 }
 Middle = UIParentMiddle {
 }
 Left = UIParentLeft {
 }
}
L = <table> {
 Stance Action Bar = "Stance Action Bar"
 Key Binding = "Key Binding"
 Myslot = "Myslot"
 Main Action Bar Page = "Main Action Bar Page"
 Ignore during Import = "Ignore during Import"
 Close = "Close"
 Import = "Import"
}

**Comment by tg123** [comment]
may i know your wow version?

**Comment by zeenk** [comment]
Retail

**Comment by hewozuoai** [comment]
the export/import options for ignoring the main action bars are also not visible due to same issue on https://github.com/tg123/myslot/blob/master/gui.lua#L254 (but no error generated as its not concatenating the text, just setting it to nil)

**Comment by hewozuoai** [comment]
i think it should be ACTIONBARS_LABEL
![image](https://github.com/tg123/myslot/assets/5726207/225d6c6d-7ef7-4a02-8878-03f79686fa6d)

**Comment by tg123** [comment]
Thanks 5.17.1 published
