### ISSUE TITLE
Can't tranfer ActionBars from RU to EN

### ISSUE THREAD

**Issue by Dahgoth** [tg123/myslot#57]
### Describe the expected behavior and what actually happened?
**Expected Behavior:** 
Importing profiles from one locale to another should work.

**Actual Behavior:**  
Clearing actionbars works, importing does not.

### Reproducing the issue.
1. Login to one locale.
2. Do export and save to profile for ActionBars.
3. Login to another locale.
4. Select the profile and hit Import.

**Lua Errors**
No response

**Comment by tg123** [comment]
myslot is designed `locale` independent

may i know what happened after your clicked the import?

**Comment by Dahgoth** [comment]
Nothing, but the chat message appeared that everything was done. It did create macroses for some reason even though I didn't exported it

**Comment by Dahgoth** [comment]
I can show you on stream or make a short video if you want. 
I should mention thought that the target caracter is level 21 and in MoP Remix event

**Comment by Dahgoth** [comment]
if it's not `locale` problem than why it's not working?

**Comment by Dahgoth** [comment]
Sorry I got my sub expired... Will do as soon as I can

**Comment by tg123** [comment]
re open if you still have issue

**Comment by Dahgoth** [comment]
I'm sorry, I retired from the game a while ago... 
I can check with some low-level toons though and make a video if the issue is still there.
