### ISSUE TITLE
i use it export and import in the same role, it have errors

### ISSUE THREAD

**Issue by angelhappyboy** [tg123/myslot#59]
here is my 
`# Myslot (https://myslot.net <- 分享你的配置)
# Wow Version: 3.4.3
# Addon Version: v5.19.3
# 时间: Fri Aug  9 01:07:07 2024
# 玩家: 幽然
# 职业: 圣骑士
# 天赋: 0/53/18
# 等级: 80
# 
# 问题/建议  farmer1992@gmail.com
# --------------------
KlYEFlTQLRwKCAgBEAEYr54BCggIAhABGKzlAwoICAMQARi4/gIKCAgEEAEY
u/0CCgcIBRADGIcBCgcIBhABGMRQCggIBxABGJT9AgoICAgQARiz/QIKCAgJ
EAEYtv4CCgYIChADGHoKBggLEAMYewoICAwQAhicoAIKBwgNEAEYzmcKCAgO
EAEYjv0CCgcIDxABGPsmCgcIEBABGNhQCggIERABGIz5AQoICBMQAhi34AEK
CAgUEAIYkKsCCggIFhABGK+eAQoICBoQAhiTugIKCAgbEAIYscwCCggIHBAC
GM7BAgoICB0QAhiH0AIKCAgeEAIYpf4CCggIHxACGMC+AgoICCAQARigoQMK
CAghEAEYn6EDCggIIhABGNykAQoICCMQARjGnQEKCAgkEAEYxZ0BCggIJhAB
GKrKAQoICCcQARiq/gIKCAgoEAEYpv4CCggIKRABGKvKAQoICCoQARj5nQEK
CAgrEAEYqP4CCggILBABGKT+AgoICC0QARivowEKCAguEAEYtMkBCggILxAB
GJefAQoICDAQARigpBUKBwgxEAEYlAgKBggyEAMYAgoGCDMQAxh8CggINBAB
GLH9AgoICDUQARiO/QIKBwg3EAMYgwEKCAg5EAIYnbkCCggIOhACGLS7AgoI
CDsQARi64AEKBwg8EAMYhQEKBgg9EAMYeQoHCD4QAxiCAQoHCD8QARjyAwoH
CEAQARiOCAoICEIQAhiltgIKBwhDEAEYnDYKBwhEEAMYhQEKCAhFEAEYqJoB
CgcIRhADGIcBCggIRxABGJypAwoHCEgQAxiBAQoICIUBEAMYhwEKCAiGARAD
GIEBCggIiAEQARjYUAoJCIsBEAEYjPkBCgkIjQEQAhi34AEKCQiOARACGJCr
AhIOCAISBAhwEAAaBAhFEAASDggDEgQIbhAAGgQIRBAAEggIBBIECHEQABII
CAUSBAhvEAASCAgGEgQIUxAAEggIBxIECEYQABIOCAgSBAh9EAAaBAgtEAAS
DggLEgQIZxAAGgQIERAAEhgI//8DEgQIRRABegxTVEFSVEFVVE9SVU4SCAgM
EgQIbRAAEggIDRIECGwQABIICA4SBAh5EAASCAgQEgQIdBAAEggIERIECGUQ
ABIICBISBAhpEAASCAgTEgQIaBAAEggIFBIECGgQARIICBcSBAhpEAISCAgY
EgQIaBACEggIGRIECGgQaxIOCBoSBAhXEAAaBAg4EAASDggbEgQIORAAGgQI
RxAAEg4IHBIECFIQABoECDoQABIOCB0SBAg7EAAaBAhUEAASDggeEgQIQRAA
GgQIPBAAEg4IHxIECFEQABoECD0QABIOCCASBAg+EAAaBAhWEAASDgghEgQI
WBAAGgQIPxAAEg4IIhIECEAQABoECEMQABIOCCMSBAg3EAAaBAhCEAASDggk
EgQIXBAAGgQIWxAAEg4IJRIECFoQABoECF0QABIICCYSBAgBEAISCAgnEgQI
AhACEggIKBIECAMQAhIICCkSBAgEEAISCAgqEgQIBRACEggIKxIECAYQAhII
CCwSBAgHEAISCAgtEgQICBACEggILhIECAkQAhIICC8SBAgKEAISCAgwEgQI
OBACEggIMRIECDkQAhIICDISBAg6EAISCAgzEgQIOxACEggINBIECDwQAhII
CDUSBAg9EAISCAg2EgQIPhACEggINxIECD8QAhIICDgSBAhAEAISCAg5EgQI
NxACEggIOhIECDgQARIICDsSBAg5EAESCAg8EgQIOhABEggIPRIECDsQARII
CD4SBAg8EAESCAg/EgQIPRABEg4IQBIECHAQARoECH4QARIOCEESBAhuEAEa
BAh/EAESCQjGARIECFcQARIJCMcBEgQIRxABEgkIyAESBAhSEAESCQjJARIE
CFQQARIJCMoBEgQIShAAEgkIywESBAhgEAASCQjMARIECFYQARIJCM0BEgQI
WBABEgkIzgESBAhDEAESCQjPARIECH8QABIJCNABEgQIfhAAEgkI0QESBAgQ
EAASCQjSARIECFMQARIJCNMBEgQIRBABEgkI1AESBAhGEAESCAhUEgQIchAA
EggIVRIECHIQARIICFYSBAhyEAISCAhXEgQIchBrEggIYRIECAEQARIICGIS
BAgCEAESCAhjEgQIAxABEggIZBIECAQQARIICGUSBAgFEAESCAhqEgQIVhAC
EgkIhgESBAh1EAASCAh2EgQIDBAAEggIeBIECAkQABIICHkSBAgKEAASCAh6
EgQICxAAEggIexIECEIQARIJCIQBEgQIVRAAEhwI//8DEgQISxAAehBUT0dH
TEVDSEFSQUNURVIxEgkIggESBAhIEAASCQi3AhIECFAQARIICH0SBAhQEAAS
CAh/EgQISRABEgkIgQESBAhOEAASCQiFARIECEwQABIJCIgBEgQITRAAEgkI
kwESBAhNEAESCQiSARIECH0QARIJCJYBEgQIWRAAEgkIlwESBAhZEAESCQiK
ARIECE8QABIJCLUCEgQISRAAEgkInAESBAh8EAASCQidARIECHsQABIJCJ4B
EgQITRACEgkInwESBAhTEAISCQigARIECF0QAhIJCKEBEgQIXBACEgkIowES
BAhaEAMSCQikARIECFIQAhIKCKUBEgUIgQEQABIJCLQBEgQIaxAAEgkItQES
BAhqEAASCQj9ARIECAEQABIJCPwBEgQIAhAAEgkI+wESBAgDEAASCQj6ARIE
CAgQABIJCPkBEgQIBhAAEgkI+AESBAgFEAASCQj3ARIECAQQABIJCPYBEgQI
BxAAEgkI/wESBAgyEAASCQiAAhIECC4QABIJCIECEgQIMBAAEgkIhAISBAh+
EAISCQiFAhIECH8QAhqhAQoJRGVjdXJzaXZlEokBL3N0b3BjYXN0aW5nCi9j
YXN0IFtAbW91c2VvdmVyLG5vbW9kLGV4aXN0c10g5riF5rSB5pyvOyAgW0Bt
b3VzZW92ZXIsZXhpc3RzLG1vZDpjdHJsXSDmuIXmtIHmnK87IFtAbW91c2Vv
dmVyLGV4aXN0cyxtb2Q6c2hpZnRdIOa4hea0geacrwoYASIGMTM0NDAwGkEK
EU1KRTogUmFuZG9tIE1vdW50EiIvcnVuIENfTW91bnRKb3VybmFsLlN1bW1v
bkJ5SUQoMCkKGAIiBjEzMjE2MRqCAQoBIBJzI3Nob3d0b29sdGlwIOelnuWc
o+eJuueJsgovc3RvcGNhc3RpbmcKL2NhbmNlbGF1cmEg56We5Zyj54m654my
Ci9jYXN0IOelnuWco+eJuueJsgoveSDlm6LpmJ/lh4/kvKQyMCXvvIzmjIHn
u60256eSChh5IgYyNTM0MDAaTAoBIBI9I3Nob3d0b29sdGlwIOWco+ebvuac
rwovY2FuY2VsQXVyYSDlnKPnm77mnK8KL2Nhc3Qg5Zyj55u+5pyvChh6IgYx
MzU4OTYaigEKASASeyNzaG93dG9vbHRpcCBbaGFybSxleGlzdHNd5oSk5oCS
5LmL6ZSkO+a4hea0geacrwovY2FzdCBbaGFybSxleGlzdHNd5oSk5oCS5LmL
6ZSkO1toZWxwLGV4aXN0c13muIXmtIHmnK87W0BwbGF5ZXJd5riF5rSB5pyv
Chh7IgYxMzU5NTMamgEKASASigEjc2hvd3Rvb2x0aXAg5L+d5oqk5LmL5omL
Ci9jYW5jZWxhdXJhIOS/neaKpOS5i+aJiwovY2FzdCBbbm9oYXJtXVt0YXJn
ZXQ9dGFyZ2V0dGFyZ2V0LCBub2hhcm1dIOS/neaKpOS5i+aJiwovdGFyZ2V0
bGFzdGVuZW15Ci9zdGFydGF0dGFjawoYfCIGMTM1OTY0GrIBCgblhYnnjq8S
nQEvY2FzdHNlcXVlbmNlIHJlc2V0PTEyMCDlhYnnjq/mjozmj6EKL2Nhc3Qg
W2hlbHBd5Zyj5YWJ5pyvKOetiee6pyAxMyk7IFt0YXJnZXQ9dGFyZ2V0dGFy
Z2V0LCBoZWxwXSDlnKPlhYnmnK8o562J57qnIDEzKTtbdGFyZ2V0PXBsYXll
cl0g5Zyj5YWJ5pyvKOetiee6pyAxMykKGH0iBjEzNDQwMBrRAgoD5Y2VEr8C
I3Nob3d0b29sdGlwCi9zdGFydGF0dGFjawovY2FzdHNlcXVlbmNlIHJlc2V0
PTYsY29tYmF0LGFsdCDmmbrmhaflrqHliKQs5Y2B5a2X5Yab5omT5Ye7LOWl
ieeMrizljYHlrZflhpvmiZPlh7ss5pm65oWn5a6h5YikLOelnuWco+mjjuaa
tCzljYHlrZflhpvmiZPlh7ss6amx6YKq5pyvLOWlieeMrizljYHlrZflhpvm
iZPlh7ss5pm65oWn5a6h5YikLOWNgeWtl+WGm+aJk+WHuyznpZ7lnKPpo47m
mrQs5Y2B5a2X5Yab5omT5Ye7LOaZuuaFp+WuoeWIpCzlpYnnjK4s5Y2B5a2X
5Yab5omT5Ye7LOmpsemCquacryznpZ7lnKPpo47mmrQs5Y2B5a2X5Yab5omT
5Ye7Chh+IgYxMzU4OTEaawoM5a6h5Yik5byA5oCqElEjc2hvd3Rvb2x0aXAK
L3N0YXJ0YXR0YWNrCi9jYXN0c2VxdWVuY2UgcmVzZXQ9OCDnpZ7lnKPkuYvn
m74s5pm65oWn5a6h5YikLOWlieeMrgoYfyIGMTM1ODgwGkEKBuaBs+axghIs
L2NhbmNlbGF1cmEg56We5Zyj5oGz5rGCCi9jYXN0IOelnuWco+aBs+axggoY
gAEiBjIzNzUzNxpUCgbmmrTlj5ESPyNzaG93dG9vbHRpcCDlpI3ku4fkuYvm
gJIKL2Nhc3Qg5aSN5LuH5LmL5oCSCi91c2Ug6YCf5bqm6I2v5rC0ChiBASIG
MTM1ODc1GlMKA+atoxJBI3Nob3d0b29sdGlwIOato+S5iemYsuW+oQovY2Fz
dCDmraPkuYnpmLLlvqEKL2Nhc3Qg5Y+s5ZSk5Yab6amsIAoYggEiBjEzNTA2
OBpnCgzmraPkuYnkuYvplKQSTCNzaG93dG9vbHRpcAovc3RhcnRhdHRhY2sK
L2Nhc3RzZXF1ZW5jZSByZXNldD01LjUg5q2j5LmJ5LmL6ZSkLOato+S5ieeb
vuWHuwoYgwEiBjIzNjI1MxpnCgzmraPkuYnnm77lh7sSTCNzaG93dG9vbHRp
cAovc3RhcnRhdHRhY2sKL2Nhc3RzZXF1ZW5jZSByZXNldD01LjUg5q2j5LmJ
55u+5Ye7LOato+S5ieS5i+mUpAoYhAEiBjIzNjI2NRqDAQoG54K45by5Em4j
c2hvd3Rvb2x0aXAKL2NsZWFydGFyZ2V0Ci9zdG9wY2FzdGluZwovdXNlIFtA
cGxheWVyXeeIhueCuOivsemltQovdXNlIDYKL3RhcmdldGxhc3R0YXJnZXQK
L2Nhc3Qg5Y+s5ZSk5Yab6amsChiFASIGMTM1ODI2GtoBCgbnibrnibISxAEj
c2hvd3Rvb2x0aXAg54m654my5LmL5omLCi9jYXN0c2VxdWVuY2UgcmVzZXQ9
MTIwIOeJuueJsuS5i+aJiyznpZ7lnKPnibrnibIKL2Nhc3QgW2hlbHBd5Zyj
5YWJ5pyvKOetiee6pyAxMyk7IFt0YXJnZXQ9dGFyZ2V0dGFyZ2V0LCBoZWxw
XSDlnKPlhYnmnK8o562J57qnIDEzKTtbdGFyZ2V0PXBsYXllcl0g5Zyj5YWJ
5pyvKOetiee6pyAxMykKGIYBIgYxMzU5NjYaTwoD55u+Ej0jc2hvd3Rvb2x0
aXAg5Zyj5rSB5oqk55u+Ci9jYXN0IFt0YXJnZXQ9cGxheWVyXSDlnKPmtIHm
iqTnm74KGIcBIgYyMzYyNDlwKnoG5bm954S2
# --------------------
# END OF MYSLOT`
i export and import in the same role but it show up errors
![d23ce635ccaae5d5885afa4490809e9](https://github.com/user-attachments/assets/7e3f7f50-43fc-4a44-82f7-5796baacb1ef)
i only use myslot and do the export and import .
it show up errors，either.
i dont konw how to fix it, or any thing i can do.

**Comment by tg123** [comment]
this is due to some macro in bonus bar 6 (slot 133 - 144)
typically, this should not happen

could you please share `/dump GetActionInfo(133)` ?
