### ISSUE TITLE
有时候恢复键位会丢失几个

### ISSUE THREAD

**Issue by leveychen** [tg123/myslot#6]
大佬，有个问题，默认配置导出键位之后，再导入键位，会出现一小部分键位没有正确还原的现象。不知是否我使用上的问题

**Comment by tg123** [comment]
看看测试版还丢吗 
https://www.curseforge.com/wow/addons/myslot/files/2949541

**Comment by leveychen** [comment]
测试版还是会丢失，经多次测试，都是 Ctrl+鼠标侧键 的按键会丢失。

**Comment by Lillyann1542** [comment]
大大你好，我也遇到相同問題，導入其他人的myslot配置，鍵位有些不會改動。不知道是哪邊有問題？

**Comment by tg123** [comment]
请问是不是由其他插件创建的案件
如果是 myslot没办法检查到
