### ISSUE TITLE
Suggestion minimapicon

### ISSUE THREAD

**Issue by Addonman** [tg123/myslot#63]
Can you add option to remove mini map icon profile window and can you make that option in options menu to effect every char not just one?

**Comment by tg123** [comment]
duplicate #61

it is in esc -> option -> myslot to turn it off

**Comment by Addonman** [comment]
I suggested to put that option in profile window simply because now you have to go into diff window to get it done when it would be easier to have it in profile window where ppl probably would spend most of time when using your addon.
Also how many people would like to see mini map icon on one char and not on another char? I think logically it should be account based option not per char option.
Just a thought.

**Comment by tg123** [comment]
will add a settings shortcut on title bar

i did a very ugly design before, so it was not released

**Comment by Addonman** [comment]
10x
