### ISSUE TITLE
[feature] Backup on import

### ISSUE THREAD

**Issue by Goten87** [tg123/myslot#65]
i just wanted to add my dragon fligh bar to my existing profile (paladin) and well i just exported the dragon fligh bar and tryed to import it and it deleted all other items is there a way you can make it that there is a full backup made befor the import is happen so we can referd to it if we do something wrong

or have the data in the export to ignore all things that we do on the export as well in the import 

(i just lost my compleet profile that i setup with all my action bars)

**Comment by tg123** [comment]
thanks 
this is under development 
will be released soon

**Comment by Goten87** [comment]
Thank god xD
