### ISSUE TITLE
Bug? Ignore unlearned skill Switch Flight Style (SpellID 460003)

### ISSUE THREAD

**Issue by leifan8440** [tg123/myslot#69]
![QQ截图20241015145300](https://github.com/user-attachments/assets/660e3160-af03-42b1-a3ef-bf68b74d7403)

**Comment by tg123** [comment]
are you sure you know the spell
https://www.wowhead.com/spell=460003 ?'


myslot cant pick it then report err

**Comment by leifan8440** [comment]
sure, i know, 80level

**Comment by tg123** [comment]
fixed in v5.22.2
