### ISSUE TITLE
Keybinds not changing when using a myslot profile

### ISSUE THREAD

**Issue by javedbartlett** [tg123/myslot#7]
When I import a profile that I just created, it will not import the keybinds

**Comment by tg123** [comment]
could you please show me the detail repro steps?

**Comment by javedbartlett** [comment]
> could you please show me the detail repro steps?

This was on beta. I just export profile, then click save. I switch to a different character, click import and the spells are in the correct places but the keybinds did not come over.

**Comment by tg123** [comment]
tbc fixed
https://www.wowace.com/projects/myslot/files/3317087
