### ISSUE TITLE
5.22.3 bug: chat spam "No player named 'ature suggests character names, you can use Tab or <Shift> Tab to select a name from the list.' is currently playing."

### ISSUE THREAD

**Issue by thefowles1** [tg123/myslot#73]
Since updating to 5.22.3, this text constantly spams in my chat:
`No player named 'ature suggests character names, you can use Tab or <Shift> Tab to select a name from the list.' is currently playing.`

![image](https://github.com/user-attachments/assets/ecf1ea45-c362-49f2-aadc-e11f65ac0ae6)

Confirmed caused by MySlot v 5.22.3, as the issue began today & it is the only addon that updated today (and downgrading to 5.22.2 clears the issue).

**Comment by tg123** [comment]
could you please disable all other addons
the message is not from myslot and 5.22.3 only bump toc to fit latest wow version, no any code changes

**Comment by thefowles1** [comment]
Huh, yeah, after updating again the spam does not occur, but no other add-ons have updated between then and now. No idea what the source is but you appear to be correct. My apologies.
