### ISSUE TITLE
Older versions inaccessible

### ISSUE THREAD

**Issue by fondlez** [tg123/myslot#75]
Hello,

What happened to all the old versions of MySlot addon? According to Curseforge and WoWAce, MySlot has existed all the way back since 2012, yet only two versions are listed for Retail.

Where could I download older complete versions, please?

**Comment by tg123** [comment]
first version myslot is back to 2008

in 2012, i re-wrote the whole addon and introduced protobuf, so it is a breaking change to `older` version before onboarding to  wowace.


if you are looking for version that support `non-official` wow which is based on `pre-ctm` client.
personally, i do not encourage so.

**Comment by fondlez** [comment]
This is what I see in Curseforge and wowace:

![curseforge-myslot-download](https://github.com/user-attachments/assets/132403a0-3641-4f76-980a-64c76c0054e0)
![wowace-myslot-download](https://github.com/user-attachments/assets/5e7fcb13-406d-4d39-a9a1-0538bac434ea)

as if someone has gone back and deleted every single version of the addon that has ever existed, except the latest two versions.

I do not know why and I would like access to various versions of those prior versions, please.

**Comment by tg123** [comment]
i hide those older versions. typically, older versions would not have latest bugfix or features, it might confuse players.
downloading latest version is always suggested before filing a bug.

that is why i hide unsupported versions.

**Comment by fondlez** [comment]
I see. May I trouble you for the last (post-"CTM"?) version of the addon that supports Mists of Pandaria 5.4.8, please?

**Comment by tg123** [comment]
[Myslot-v5.1.1.54-2-g35f1712.zip](https://github.com/user-attachments/files/18243985/Myslot-v5.1.1.54-2-g35f1712.zip)
